# 🧊 1. PyTorch Fundamentals 🧊

In [1]:
print("hello world")

hello world


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.9.0+cpu


### 🧊 Tensors - Tensors are multi-dimensional arrays with a uniform type
![Tensor](images/tensor.png)

In [4]:

### kinds of Tensors

### 1. scalar

scalar = torch.tensor(7)
scalar          ##print tensor
scalar.item()   ## get value of tensor in int
# scalar.ndim   # 0


7

In [5]:
### 2. vector
vector = torch.tensor([7, 7])
vector
# vector.ndim  # 1

tensor([7, 7])

In [6]:
### 3. matrix
Matrix = torch.tensor([[7, 8],
                       [9, 10]])
Matrix
# Matrix.ndim     #2

tensor([[ 7,  8],
        [ 9, 10]])

In [7]:
### 4. higher dimensional tensor
Tensor = torch.tensor([[[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]],
                        
                        [[10, 11, 12],
                         [13, 14, 15],
                         [16, 17, 18]],
                        
                        [[19, 20, 21],
                         [22, 23, 24],
                         [25, 26, 27]]])
Tensor 
Tensor.shape  ## get shape of tensor
Tensor.ndim  ## get number of dimensions
# Tensor.dtype ## get datatype of tensor

3

In [8]:
### Random Tensors

random_tensor = torch.rand(2,3)
random_tensor


# Create an image from random tensors
random_image_size_tensor = torch.rand(size=(244,244,3)) # height, width, color (R, G, B)
random_image_size_tensor

tensor([[[3.9050e-01, 2.8354e-01, 4.8309e-01],
         [6.4493e-02, 8.6227e-01, 7.1763e-01],
         [4.4928e-01, 3.8784e-02, 4.9365e-01],
         ...,
         [1.5599e-01, 3.9907e-01, 1.2174e-01],
         [6.6734e-01, 9.4753e-01, 2.5743e-01],
         [9.2382e-01, 1.0602e-01, 9.5790e-01]],

        [[9.7535e-01, 7.6385e-01, 4.1498e-01],
         [5.7846e-01, 6.5158e-01, 5.4719e-01],
         [7.0437e-01, 7.2526e-01, 3.5958e-03],
         ...,
         [2.6526e-01, 4.7094e-01, 4.2736e-01],
         [9.7582e-01, 3.4061e-01, 5.2243e-01],
         [5.3670e-01, 8.1464e-01, 7.3085e-01]],

        [[9.2587e-01, 9.7541e-01, 5.3759e-01],
         [6.5273e-01, 8.8772e-01, 6.2641e-01],
         [2.4834e-01, 8.5819e-03, 2.2798e-01],
         ...,
         [6.8659e-01, 4.9252e-01, 6.9585e-01],
         [6.6720e-01, 3.4672e-01, 8.2950e-01],
         [3.7947e-01, 4.0562e-01, 6.7613e-01]],

        ...,

        [[6.3921e-01, 6.5847e-01, 4.4872e-01],
         [8.6797e-01, 4.1383e-01, 1.6737e-01]

In [9]:
### Range of tensors

one_to_ten = torch.arange(0, 10) # (start=0, end=10, step=1)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
### Create tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### 🧊 Tensor Datatypes

In [11]:
# Float 32 --- 32 bits, decimal numbers

float_32_tensor = torch.tensor([1.0, 2.0, 3.0],
                               dtype=None,          # default dtype is float32 
                               device=None,         # device can be "cpu" or "cuda"
                               requires_grad=False) # whether or not to track gradients

print(float_32_tensor.dtype)

torch.float32


In [12]:
# Change Datatype of tensors
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [13]:
# Details of Tensor
a_tensor = torch.rand(2, 4)
a_tensor

print(a_tensor)
print(f"Datatype of tensor: {a_tensor.dtype}")
print(f"Shape of tensor: {a_tensor.shape}")
print(f"Device of tensor: {a_tensor.device}")

tensor([[0.0743, 0.2372, 0.2852, 0.7391],
        [0.6021, 0.1663, 0.3451, 0.4147]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([2, 4])
Device of tensor: cpu


### 🧊 Manipulating Tensors

In [14]:
#Add

tensor = torch.tensor([1,2,3])
tensor + 10 # alternative, torch.add(tensor, 10)


tensor([11, 12, 13])

In [15]:
# Multiply
tensor * 10

tensor([10, 20, 30])

In [16]:
# Subtract
tensor - 10

tensor([-9, -8, -7])

In [17]:
# Division


In [18]:
# Multiplication (http://matrixmultiplication.xyz/)
#### 1. Element-wise multiplications

print(tensor * tensor)


tensor([1, 4, 9])


In [19]:
#### 2. Matrix multiplication (dot product)
# Must Satifies some rules of multiplication of tensors otherwise throws errors:
# - Inner Dimensions must match:
#   (3, 2) @ (3, 2) ❌
#       |_____|
#   (2, 3) @ (3, 2) ✔️
#   (3, 2) @ (2, 3) ✔️

# - The resulting matrix has the shape of **outer dimension**:
#   (2, 3) @ (3, 2)   -->  (2, 2) ✔️


# %%time 
torch.matmul(tensor, tensor) # aliases.. tensor @ tensor or simply torch.mm(t, t)

tensor(14)

### 🧊 Common Troubleshooting Errors: 

In [20]:
# Shape errors
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensor_A.shape

torch.Size([3, 2])

In [21]:
tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]])
tensor_B.shape

torch.Size([3, 2])

In [22]:
# Use **transpose**  - switches the axes or dimensions of a given tensor
tensor_fixed_B = tensor_B.T # and now it satisfies the shape tensor_A * tensor_B = [3, 2] * [2, 3]

tensor_A @ tensor_fixed_B

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### 🧊 Tensor Aggregations - min, max, mean, sum etc

In [23]:
# Create a tensor
x = torch.arange(1, 10, 1)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [24]:
# min
torch.min(x) , 'or', x.min() 

(tensor(1), 'or', tensor(1))

In [25]:
# max
torch.max(x) , 'or', x.max() 

(tensor(9), 'or', tensor(9))

In [26]:
# mean - must be of float32
torch.mean(x.type(torch.float32)) , 'or', x.type(torch.float32).mean() 

(tensor(5.), 'or', tensor(5.))

In [27]:
# sum
torch.sum(x) , 'or', x.sum() 

(tensor(45), 'or', tensor(45))

In [28]:
# Finding the positional min and max 
x.argmin()


tensor(0)

In [29]:
x.argmax()

tensor(8)

### 🧊 Tensor Shape Manipulation - reshaping, stacking, squeezing and unsqueezing

In [30]:
# Reshaping - reshapes a tensor to a defined shape

# View - Return a view of an imput tensor of certain shape but keep the same memory as the original tensor

# stacking - combine multiple tensors on top of each other (vstack) or side by side

# Squeeze - removes all `1` dimension from a tensor
# Unsqueeze - add a `1` dimension from a tensor
# Permute - return a view of the input with dimensions permuted (swapped) in a certain way

x.shape

x_reshaped = x.reshape(1, 9) #but 2,9 won't be compatible as 2*9 = 18 and  not 9
x_reshaped, x


(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [34]:
# Changing the view ()
z = x.view(3 , 3)
z, x


(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))