# 🧊 1. PyTorch Fundamentals 🧊

In [1]:
print("hello world")

hello world


In [2]:
!nvidia-smi

Sun Jan 11 14:32:49 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   49C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.9.0+cu126


### 🧊 Tensors - Tensors are multi-dimensional arrays with a uniform type
![Tensor](images/tensor.png)

In [4]:

### kinds of Tensors

### 1. scalar

scalar = torch.tensor(7)
scalar          ##print tensor
scalar.item()   ## get value of tensor in int
# scalar.ndim   # 0


7

In [5]:
### 2. vector
vector = torch.tensor([7, 7])
vector
# vector.ndim  # 1

tensor([7, 7])

In [6]:
### 3. matrix
Matrix = torch.tensor([[7, 8],
                       [9, 10]])
Matrix
# Matrix.ndim     #2

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
### 4. higher dimensional tensor
Tensor = torch.tensor([[[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]],
                        
                        [[10, 11, 12],
                         [13, 14, 15],
                         [16, 17, 18]],
                        
                        [[19, 20, 21],
                         [22, 23, 24],
                         [25, 26, 27]]])
Tensor 
Tensor.shape  ## get shape of tensor
Tensor.ndim  ## get number of dimensions
# Tensor.dtype ## get datatype of tensor

3

In [8]:
### Random Tensors

random_tensor = torch.rand(2,3)
random_tensor


# Create an image from random tensors
random_image_size_tensor = torch.rand(size=(244,244,3)) # height, width, color (R, G, B)
random_image_size_tensor

tensor([[[0.8970, 0.1069, 0.6865],
         [0.4452, 0.1119, 0.1784],
         [0.1969, 0.8112, 0.6223],
         ...,
         [0.1229, 0.4581, 0.0301],
         [0.7471, 0.9396, 0.5546],
         [0.5640, 0.4590, 0.8549]],

        [[0.4929, 0.4458, 0.0328],
         [0.7792, 0.8952, 0.7494],
         [0.1564, 0.5276, 0.9192],
         ...,
         [0.5009, 0.5131, 0.6217],
         [0.2367, 0.5481, 0.5909],
         [0.8780, 0.1613, 0.2996]],

        [[0.9283, 0.4958, 0.6405],
         [0.8911, 0.6843, 0.1812],
         [0.7625, 0.5231, 0.1726],
         ...,
         [0.5266, 0.3376, 0.9475],
         [0.5910, 0.3243, 0.4367],
         [0.1951, 0.5841, 0.0890]],

        ...,

        [[0.9027, 0.6962, 0.9148],
         [0.9395, 0.1767, 0.0153],
         [0.4414, 0.9367, 0.3694],
         ...,
         [0.0673, 0.9512, 0.4035],
         [0.8778, 0.2081, 0.7007],
         [0.1275, 0.2860, 0.6322]],

        [[0.8553, 0.6295, 0.9018],
         [0.6196, 0.4219, 0.6168],
         [0.

In [9]:
### Range of tensors

one_to_ten = torch.arange(0, 10) # (start=0, end=10, step=1)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
### Create tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### 🧊 Tensor Datatypes

In [11]:
# Float 32 --- 32 bits, decimal numbers

float_32_tensor = torch.tensor([1.0, 2.0, 3.0],
                               dtype=None,          # default dtype is float32 
                               device=None,         # device can be "cpu" or "cuda"
                               requires_grad=False) # whether or not to track gradients

print(float_32_tensor.dtype)

torch.float32


In [12]:
# Change Datatype of tensors
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [ ]:
# Details of Tensor
a_tensor = torch.rand(2, 4)
a_tensor

print(a_tensor)
print(f"Datatype of tensor: {a_tensor.dtype}")
print(f"Shape of tensor: {a_tensor.shape}")
print(f"Device of tensor: {a_tensor.device}")

tensor([[0.6616, 0.3263, 0.2856, 0.8022],
        [0.0142, 0.6121, 0.8859, 0.3814]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([2, 4])
Device of tensor: cpu


### 🧊 Manipulating Tensors

In [14]:
#Add

tensor = torch.tensor([1,2,3])
tensor + 10 # alternative, torch.add(tensor, 10)


tensor([11, 12, 13])

In [15]:
# Multiply
tensor * 10

tensor([10, 20, 30])

In [16]:
# Subtract
tensor - 10

tensor([-9, -8, -7])

In [17]:
# Division


In [18]:
# Multiplication (http://matrixmultiplication.xyz/)
#### 1. Element-wise multiplications

print(tensor * tensor)


tensor([1, 4, 9])


In [19]:
#### 2. Matrix multiplication (dot product)
# Must Satifies some rules of multiplication of tensors otherwise throws errors:
# - Inner Dimensions must match:
#   (3, 2) @ (3, 2) ❌
#       |_____|
#   (2, 3) @ (3, 2) ✔️
#   (3, 2) @ (2, 3) ✔️

# - The resulting matrix has the shape of **outer dimension**:
#   (2, 3) @ (3, 2)   -->  (2, 2) ✔️


# %%time 
torch.matmul(tensor, tensor) # aliases.. tensor @ tensor or simply torch.mm(t, t)

tensor(14)

### 🧊 Common Troubleshooting Errors: 

In [ ]:
# Shape errors
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensor_A.shape

torch.Size([3, 2])

In [21]:
tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]])
tensor_B.shape

torch.Size([3, 2])

In [22]:
# Use **transpose**  - switches the axes or dimensions of a given tensor
tensor_fixed_B = tensor_B.T # and now it satisfies the shape tensor_A * tensor_B = [3, 2] * [2, 3]

tensor_A @ tensor_fixed_B

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### 🧊 Tensor Aggregations - min, max, mean, sum etc

In [23]:
# Create a tensor
x = torch.arange(1, 10, 1)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [24]:
# min
torch.min(x) , 'or', x.min() 

(tensor(1), 'or', tensor(1))

In [ ]:
# max
torch.max(x) , 'or', x.max() 

(tensor(9), 'or', tensor(9))

In [26]:
# mean - must be of float32
torch.mean(x.type(torch.float32)) , 'or', x.type(torch.float32).mean() 

(tensor(5.), 'or', tensor(5.))

In [27]:
# sum
torch.sum(x) , 'or', x.sum() 

(tensor(45), 'or', tensor(45))

In [28]:
# Finding the positional min and max 
x.argmin()


tensor(0)

In [29]:
x.argmax()

tensor(8)

### 🧊 Tensor Shape Manipulation - reshaping, stacking, squeezing and unsqueezing

In [ ]:
# Reshaping - reshapes a tensor to a defined shape

# View - Return a view of an imput tensor of certain shape but keep the same memory as the original tensor

# stacking - combine multiple tensors on top of each other (vstack) or side by side

# Squeeze - removes all `1` dimension from a tensor
# Unsqueeze - add a `1` dimension to a tensor at specific dim
# Permute - return a view of the input with dimensions permuted (swapped) in a certain way

x.shape

x_reshaped = x.reshape(1, 9) #but 2,9 won't be compatible as 2*9 = 18 and  not 9
x_reshaped, x


(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [31]:
# Changing the view (doesn't manupulate original tensor unlike reshape)
z = x.view(3 , 3)
z, x


(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [32]:
# Changing z changes x (shares same memory as the original input)
z[:, 0] = 5
z, x


(tensor([[5, 2, 3],
         [5, 5, 6],
         [5, 8, 9]]),
 tensor([5, 2, 3, 5, 5, 6, 5, 8, 9]))

In [33]:
# Stack - combine multiple tensors on top of each other (vstack) or side by side
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5, 2, 3, 5, 5, 6, 5, 8, 9],
        [5, 2, 3, 5, 5, 6, 5, 8, 9],
        [5, 2, 3, 5, 5, 6, 5, 8, 9],
        [5, 2, 3, 5, 5, 6, 5, 8, 9]])

In [34]:
# Squeeze - removes all single dimension from a tensor
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([5, 2, 3, 5, 5, 6, 5, 8, 9])

In [35]:
# Unsqueeze - add a single dimension to a tensor at specific dim
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed


tensor([[5, 2, 3, 5, 5, 6, 5, 8, 9]])

In [36]:
# Permute - return a view of the input with dimensions permuted (index swapped) in a certain way

x_original = torch.rand(size=(244, 244, 3)) # [height, width, color_channels]
x_permuted = x_original.permute(2, 0, 1) # [color_channels, height, width]

### 🧊 Indexing Tensors (similar to NumPy(arrays))

In [37]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [38]:
x[0][0][1], 'or', x[0, 0, 1]

(tensor(2), 'or', tensor(2))

In [39]:

# Get all values at the 0th index
x[:, 0]

tensor([[1, 2, 3]])

In [40]:
# Get all values of 0th and 1st dimension but only index 1 or 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

### 🧊 Pytorch tensors & NumPy
NumPy is a popular scientific computing library in Python. PyTorch tensors can be easily converted to and from NumPy arrays.


In [ ]:

# Numpy to Tensor:
import torch
import numpy as np
array = np.arange(1.0, 8.0) #float32
tensor = torch.from_numpy(array) #float64
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [42]:
# Tensor to Numpy:
numpy_array = tensor.numpy()
numpy_array #float32

#Note: they both tensor and NumPy don't show same memory, means pass by value

array([1., 2., 3., 4., 5., 6., 7.])

### 🧊 Reproducebility (trying to take random out of random)

How Neural network learns -> start with random numbers -> perform tensor operations -> update numbers to manke them better representation of the data -> repeat the process

To reduce randomness in our experiments, we can set a random seed. A random seed is a number that initializes the random number generator, ensuring that the sequence of random numbers generated is the same each time the code is run.


In [43]:
# Create random tensors but reproducible tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

random_tensor_A == random_tensor_B #false


RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED) # must pass on each time
random_tensor_d = torch.rand(3, 4)

random_tensor_c == random_tensor_d #true


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

### 🧊 Running tensors and Pytorch objects on the GPUs

In [49]:
!nvidia-smi

Sun Jan 11 14:39:45 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   44C    P8              9W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
# check for GPU access using Pytorch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code - best practice !!!
device = "cuda" if torch.cuda.is_available() else "cpu"
device


'cuda'

In [50]:
# Count no. of devices
torch.cuda.device_count()

1

In [52]:
# Putting tensors (and models) on the GPU
tensor = torch.tensor([1,2,3], device="cpu")

print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU 🟢
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
# Move tensor back to CPU 🔴
## if tensor is on GPU, it cant be transform to numPy as numpy only works on CPU

# tensor_on_gpu.numpy() # throws error
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
print(tensor_back_on_cpu, tensor_back_on_cpu.device)

[1 2 3] cpu
