# 🧊 1. PyTorch Fundamentals 🧊

In [5]:
print("hello world")

hello world


In [6]:
!nvidia-smi

Thu Jul  9 07:55:00 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.159.03             Driver Version: 580.159.03     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-40GB          Off |   00000000:00:05.0 Off |                    0 |
| N/A   32C    P0             51W /  400W |   16492MiB /  40960MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+-----

In [7]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.8.0+cu128


### 🧊 Tensors - Tensors are multi-dimensional arrays with a uniform type
![Tensor](images/tensor.png)

In [8]:

### kinds of Tensors

### 1. scalar

scalar = torch.tensor(7)
scalar          ##print tensor
scalar.item()   ## get value of tensor in int
# scalar.ndim   # 0


7

In [9]:
### 2. vector
vector = torch.tensor([7, 7])
vector
# vector.ndim  # 1

tensor([7, 7])

In [10]:
### 3. matrix
Matrix = torch.tensor([[7, 8],
                       [9, 10]])
Matrix
# Matrix.ndim     #2

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
### 4. higher dimensional tensor
Tensor = torch.tensor([[[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]],
                        
                        [[10, 11, 12],
                         [13, 14, 15],
                         [16, 17, 18]],
                        
                        [[19, 20, 21],
                         [22, 23, 24],
                         [25, 26, 27]]])
Tensor 
Tensor.shape  ## get shape of tensor
Tensor.ndim  ## get number of dimensions
# Tensor.dtype ## get datatype of tensor

3

In [12]:
### Random Tensors

random_tensor = torch.rand(2,3)
random_tensor


# Create an image from random tensors
random_image_size_tensor = torch.rand(size=(244,244,3)) # height, width, color (R, G, B)
random_image_size_tensor

tensor([[[0.7803, 0.8804, 0.7403],
         [0.9221, 0.4722, 0.8805],
         [0.6573, 0.3859, 0.5862],
         ...,
         [0.4623, 0.5180, 0.7885],
         [0.2699, 0.2390, 0.4165],
         [0.8811, 0.7362, 0.3098]],

        [[0.8615, 0.7168, 0.7098],
         [0.3161, 0.3708, 0.1747],
         [0.2070, 0.9029, 0.9654],
         ...,
         [0.3023, 0.3933, 0.4137],
         [0.5244, 0.7179, 0.8954],
         [0.8832, 0.2234, 0.9267]],

        [[0.3526, 0.1464, 0.3095],
         [0.8218, 0.9121, 0.0788],
         [0.7392, 0.1830, 0.8920],
         ...,
         [0.4445, 0.0088, 0.4173],
         [0.5669, 0.5487, 0.6235],
         [0.1287, 0.9701, 0.6191]],

        ...,

        [[0.0335, 0.0631, 0.5121],
         [0.8401, 0.7303, 0.9269],
         [0.5746, 0.2656, 0.0440],
         ...,
         [0.9582, 0.3955, 0.7710],
         [0.5320, 0.6007, 0.2553],
         [0.8500, 0.8906, 0.6965]],

        [[0.1668, 0.1865, 0.4113],
         [0.8938, 0.4812, 0.4495],
         [0.

In [13]:
### Range of tensors

one_to_ten = torch.arange(0, 10) # (start=0, end=10, step=1)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
### Create tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### 🧊 Tensor Datatypes

In [15]:
# Float 32 --- 32 bits, decimal numbers

float_32_tensor = torch.tensor([1.0, 2.0, 3.0],
                               dtype=None,          # default dtype is float32 
                               device=None,         # device can be "cpu" or "cuda"
                               requires_grad=False) # whether or not to track gradients

print(float_32_tensor.dtype)

torch.float32


In [16]:
# Change Datatype of tensors
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [17]:
# Details of Tensor
a_tensor = torch.rand(2, 4)
a_tensor

print(a_tensor)
print(f"Datatype of tensor: {a_tensor.dtype}")
print(f"Shape of tensor: {a_tensor.shape}")
print(f"Device of tensor: {a_tensor.device}")

tensor([[0.5183, 0.6684, 0.9232, 0.1093],
        [0.6104, 0.3476, 0.5014, 0.9819]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([2, 4])
Device of tensor: cpu


### 🧊 Manipulating Tensors

In [18]:
#Add

tensor = torch.tensor([1,2,3])
tensor + 10 # alternative, torch.add(tensor, 10)


tensor([11, 12, 13])

In [19]:
# Multiply
tensor * 10

tensor([10, 20, 30])

In [20]:
# Subtract
tensor - 10

tensor([-9, -8, -7])

In [21]:
# Division


In [22]:
# Multiplication (http://matrixmultiplication.xyz/)
#### 1. Element-wise multiplications

print(tensor * tensor)


tensor([1, 4, 9])


In [23]:
#### 2. Matrix multiplication (dot product)
# Must Satifies some rules of multiplication of tensors otherwise throws errors:
# - Inner Dimensions must match:
#   (3, 2) @ (3, 2) ❌
#       |_____|
#   (2, 3) @ (3, 2) ✔️
#   (3, 2) @ (2, 3) ✔️

# - The resulting matrix has the shape of **outer dimension**:
#   (2, 3) @ (3, 2)   -->  (2, 2) ✔️


# %%time 
torch.matmul(tensor, tensor) # aliases.. tensor @ tensor or simply torch.mm(t, t)

tensor(14)

### 🧊 Common Troubleshooting Errors: 

In [24]:
# Shape errors
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensor_A.shape

torch.Size([3, 2])

In [25]:
tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]])
tensor_B.shape

torch.Size([3, 2])

In [26]:
# Use **transpose**  - switches the axes or dimensions of a given tensor
tensor_fixed_B = tensor_B.T # and now it satisfies the shape tensor_A * tensor_B = [3, 2] * [2, 3]

tensor_A @ tensor_fixed_B

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### 🧊 Tensor Aggregations - min, max, mean, sum etc

In [27]:
# Create a tensor
x = torch.arange(1, 10, 1)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [28]:
# min
torch.min(x) , 'or', x.min() 

(tensor(1), 'or', tensor(1))

In [29]:
# max
torch.max(x) , 'or', x.max() 

(tensor(9), 'or', tensor(9))

In [30]:
# mean - must be of float32
torch.mean(x.type(torch.float32)) , 'or', x.type(torch.float32).mean() 

(tensor(5.), 'or', tensor(5.))

In [31]:
# sum
torch.sum(x) , 'or', x.sum() 

(tensor(45), 'or', tensor(45))

In [32]:
# Finding the positional min and max 
x.argmin()


tensor(0)

In [33]:
x.argmax()

tensor(8)

### 🧊 Tensor Shape Manipulation - reshaping, stacking, squeezing and unsqueezing

In [34]:
# Reshaping - reshapes a tensor to a defined shape

# View - Return a view of an imput tensor of certain shape but keep the same memory as the original tensor

# stacking - combine multiple tensors on top of each other (vstack) or side by side

# Squeeze - removes all `1` dimension from a tensor
# Unsqueeze - add a `1` dimension to a tensor at specific dim
# Permute - return a view of the input with dimensions permuted (swapped) in a certain way

x.shape

x_reshaped = x.reshape(1, 9) #but 2,9 won't be compatible as 2*9 = 18 and  not 9
x_reshaped, x


(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [35]:
# Changing the view (doesn't manupulate original tensor unlike reshape)
z = x.view(3 , 3)
z, x


(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [36]:
# Changing z changes x (shares same memory as the original input)
z[:, 0] = 5
z, x


(tensor([[5, 2, 3],
         [5, 5, 6],
         [5, 8, 9]]),
 tensor([5, 2, 3, 5, 5, 6, 5, 8, 9]))

In [37]:
# Stack - combine multiple tensors on top of each other (vstack) or side by side
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5, 2, 3, 5, 5, 6, 5, 8, 9],
        [5, 2, 3, 5, 5, 6, 5, 8, 9],
        [5, 2, 3, 5, 5, 6, 5, 8, 9],
        [5, 2, 3, 5, 5, 6, 5, 8, 9]])

In [38]:
# Squeeze - removes all single dimension from a tensor
print(f" {x_reshaped}")
x_squeezed = x_reshaped.squeeze()
x_squeezed

 tensor([[5, 2, 3, 5, 5, 6, 5, 8, 9]])


tensor([5, 2, 3, 5, 5, 6, 5, 8, 9])

In [39]:
# Unsqueeze - add a single dimension to a tensor at specific dim
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed


tensor([[5, 2, 3, 5, 5, 6, 5, 8, 9]])

In [40]:
# Permute - return a view of the input with dimensions permuted (index swapped) in a certain way

x_original = torch.rand(size=(244, 244, 3)) # [height, width, color_channels]
x_permuted = x_original.permute(2, 0, 1) # [color_channels, height, width]


### 🧊 Indexing Tensors (similar to NumPy(arrays))

In [41]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [42]:
x[0][0][1], 'or', x[0, 0, 1] #(depth, rows, columns)

(tensor(2), 'or', tensor(2))

In [43]:

# Get all values at the 0th index
x[:, 0]

tensor([[1, 2, 3]])

In [44]:
# Get all values of 0th and 1st dimension but only index 1 or 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

### 🧊 Pytorch tensors & NumPy
NumPy is a popular scientific computing library in Python. PyTorch tensors can be easily converted to and from NumPy arrays.


In [45]:

# Numpy to Tensor:
import torch
import numpy as np
array = np.arange(1.0, 8.0) #float32
tensor = torch.from_numpy(array) #float64
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [46]:
# Tensor to Numpy:
numpy_array = tensor.numpy()
numpy_array #float32

#Note: they both tensor and NumPy don't show same memory, means pass by value

array([1., 2., 3., 4., 5., 6., 7.])

### 🧊 Reproducebility (trying to take random out of random)

How Neural network learns -> start with random numbers -> perform tensor operations -> update numbers to manke them better representation of the data -> repeat the process

To reduce randomness in our experiments, we can set a random seed. A random seed is a number that initializes the random number generator, ensuring that the sequence of random numbers generated is the same each time the code is run.


In [47]:
# Create random tensors but reproducible tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

random_tensor_A == random_tensor_B #false


RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED) # must pass on each time
random_tensor_d = torch.rand(3, 4)

random_tensor_c == random_tensor_d #true


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

### 🧊 Running tensors and Pytorch objects on the GPUs

In [48]:
!nvidia-smi

Thu Jul  9 07:55:41 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.159.03             Driver Version: 580.159.03     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-40GB          Off |   00000000:00:05.0 Off |                    0 |
| N/A   32C    P0             52W /  400W |   16492MiB /  40960MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+-----

In [49]:
# check for GPU access using Pytorch
torch.cuda.is_available()

True

In [54]:
# Setup device agnostic code - best practice !!!
device = "cuda" if torch.cuda.is_available() else "cpu"
device


'cuda'

In [ ]:
# Count no. of GPUs
torch.cuda.device_count()

1

In [52]:
# Putting tensors (and models) on the GPU
tensor = torch.tensor([1,2,3], device="cpu")

print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


In [55]:
# Move tensor to GPU 🟢
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [56]:
# Move tensor back to CPU 🔴
## if tensor is on GPU, it can't be transform to numPy as numpy only works on CPU

# tensor_on_gpu.numpy() # throws error
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
print(tensor_back_on_cpu, tensor_back_on_cpu.device)

[1 2 3] cpu
